#!/usr/bin/env bash

number_of_challenges=0
if [[ -n $1 ]]; then
    number_of_challenges=$1
fi

read -d '\n' cpp_template << EOF
#include <cassert>
#include <iostream>

int main()
{
  {

  }

  {

  }

  return 0;
}

EOF

if [[ $number_of_challenges -gt 0 ]]; then
  echo "$cpp_template" > "new_file.cpp"
fi

for ((i=1; i < number_of_challenges; ++i)); do
    echo "$cpp_template" > "new_file_$i.cpp"
done

